export default function Page() {
  return (
    <div className="flex min-h-screen flex-col p-24">
      <h1 className="mb-4 text-2xl font-bold">Privacy</h1>
      <p className="mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, quas consequatur harum, distinctio exercitationem mollitia eos, at sunt eveniet sit eius praesentium impedit sapiente ut doloremque? Accusamus ipsum, laboriosam, facilis sunt repudiandae vero quo numquam dolor, amet exercitationem quos qui odit molestiae quia asperiores ex nesciunt quod consectetur quaerat? Incidunt?</p>
      <p className="mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, quas consequatur harum, distinctio exercitationem mollitia eos, at sunt eveniet sit eius praesentium impedit sapiente ut doloremque? Accusamus ipsum, laboriosam, facilis sunt repudiandae vero quo numquam dolor, amet exercitationem quos qui odit molestiae quia asperiores ex nesciunt quod consectetur quaerat? Incidunt?</p>
      <p className="mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, quas consequatur harum, distinctio exercitationem mollitia eos, at sunt eveniet sit eius praesentium impedit sapiente ut doloremque? Accusamus ipsum, laboriosam, facilis sunt repudiandae vero quo numquam dolor, amet exercitationem quos qui odit molestiae quia asperiores ex nesciunt quod consectetur quaerat? Incidunt?</p>
      <p className="mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, quas consequatur harum, distinctio exercitationem mollitia eos, at sunt eveniet sit eius praesentium impedit sapiente ut doloremque? Accusamus ipsum, laboriosam, facilis sunt repudiandae vero quo numquam dolor, amet exercitationem quos qui odit molestiae quia asperiores ex nesciunt quod consectetur quaerat? Incidunt?</p>
      <p className="mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, quas consequatur harum, distinctio exercitationem mollitia eos, at sunt eveniet sit eius praesentium impedit sapiente ut doloremque? Accusamus ipsum, laboriosam, facilis sunt repudiandae vero quo numquam dolor, amet exercitationem quos qui odit molestiae quia asperiores ex nesciunt quod consectetur quaerat? Incidunt?</p>
      <p className="mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, quas consequatur harum, distinctio exercitationem mollitia eos, at sunt eveniet sit eius praesentium impedit sapiente ut doloremque? Accusamus ipsum, laboriosam, facilis sunt repudiandae vero quo numquam dolor, amet exercitationem quos qui odit molestiae quia asperiores ex nesciunt quod consectetur quaerat? Incidunt?</p>
      <p className="mb-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Necessitatibus, quas consequatur harum, distinctio exercitationem mollitia eos, at sunt eveniet sit eius praesentium impedit sapiente ut doloremque? Accusamus ipsum, laboriosam, facilis sunt repudiandae vero quo numquam dolor, amet exercitationem quos qui odit molestiae quia asperiores ex nesciunt quod consectetur quaerat? Incidunt?</p>
    </div>
  )
}