import type { Metadata } from "next";
import { Cormorant, Cabin } from "next/font/google";
import "./globals.css";
import { Navbar } from "../../components/Navbar";
import { AdditionalLinks } from "../../components/AdditionalLinks";
import { NewsletterForm } from "../../components/NewsletterForm";

const cormorant = Cormorant({
  subsets: ["latin"],
  variable: "--font-cormorant",
});

const cabin = Cabin({
  subsets: ["latin"],
  variable: "--font-cabin",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${cormorant.variable} ${cabin.variable} font-sans`}>
        <Navbar />
        <main className="px-2 pb-20">
          <div className="mx-auto max-w-screen-md">{children}</div>
          <NewsletterForm />
          <AdditionalLinks />
        </main>
      </body>
    </html>
  );
}
