import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import { LeftSidebar } from "./components/LeftSidebar";
import { RightSidebar } from "./components/RightSidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <main className="grid grid-cols-1 grid-rows-3 gap-4 lg:grid-cols-12">
          <LeftSidebar />
          <RightSidebar />
          <div className="col-span-8 col-start-3 row-start-1 pb-20">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
