export const designerRoles = [
  "3D Designer",
  "Art Director",
  "Brand Designer",
  "Consultant",
  "Creative Director",
  "Design Strategist",
  "Fashion Designer",
  "Founder",
  "Freelancer",
  "Game Designer",
  "Graphic Designer",
  "Illustrator",
  "Indie Maker",
  "Industrial Designer",
  "Information Architect",
  "Interaction Designer",
  "Interior Designer",
  "Motion Designer",
  "Product Designer",
  "Self-Employed",
  "Service Designer",
  "UI/UX Designer",
  "UX Researcher",
  "Visual Designer",
  "Web Designer",
];
