export const designerRoles = [
  "Graphic Designer",
  "UI/UX Designer",
  "Product Designer",
  "Web Designer",
  "Visual Designer",
  "Interaction Designer",
  "Motion Designer",
  "Brand Designer",
  "Illustrator",
  "3D Designer",
  "Industrial Designer",
  "Game Designer",
  "Fashion Designer",
  "Interior Designer",
  "Art Director",
  "Creative Director",
  "Design Strategist",
  "UX Researcher",
  "Information Architect",
  "Service Designer",
];
