export const plausibleEvents = {
  VIEW_APP: "view-app",
  VIEW_BOOK: "view-book",
  VIEW_TOOL: "view-tool",
  QUIZ_STARTED: "quiz-started",
  QUIZ_QUESTION_ANSWERED: "quiz-question-answered",
  QUIZ_EMAIL_ENTERED: "quiz-email-entered",
  QUIZ_COMPLETED: "quiz-completed",
  QUIZ_RESULT_VIEWED: "quiz-result-viewed",
  CONTACT_EMAIL: "contact-email",
  VIEW_WEBSITE: "view-website",
  VIEW_COMPANY: "view-company",
  VIEW_LINKEDIN: "view-linkedin",
  VIEW_X: "view-x",
  VIEW_INSTAGRAM: "view-instagram",
  VIEW_dribbble: "view-dribbble",
} as const;
